---
- name: Execute the shell script
  hosts: workers
  become: true
  vars:
    external_port: "{{ external_port }}"
    internal_port: "{{ internal_port }}"
    docker_image: "{{ docker_image }}"
    domain_name: "{{ domain_name }}"
    app_port: "{{ external_port}}"
  tasks:
    - name: Deploy with Docker
      command: docker run -d -p "{{ external_port }}":"{{ internal_port }}" "{{ docker_image }}"

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Setup Nginx Server Block
      template:
        src: nginx_domain.conf.j2
        dest: "/etc/nginx/sites-available/{{ domain_name }}"

    - name: Enable Nginx configuration
      file:
        src: "/etc/nginx/sites-available/{{ domain_name }}"
        dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
        state: link

    - name: Reload Nginx to apply changes
      service:
        name: nginx
        state: reloaded