---
- name: Execute the shellscript 
  hosts: workers
  become: true
  tasks:
    - name: Create a directory 
      file: 
        path: /ubuntu/folder1
        state: directory
        mode: 0755

    - name: Copy the shellscript to the remote server
      copy:
        src: ../shellscript/createfolder.sh
        dest: /ubuntu/folder1/
        mode: '0755'

    - name: Execute the shellscript
      command: bash /ubuntu/folder1/createfolder.sh