---
- name: Execute the shellscript
  hosts: workers
  become: true
  vars:
    external_port: "{{ external_port }}"
    internal_port: "{{ internal_port }}"
    docker_image: "{{ docker_image }}"

  tasks:
    - name: Deploy with docker
      command: docker run -dp "{{ external_port }}":"{{ external_port }}" "{{ docker_image }}"