---
- name: Execute the shell script
  hosts: workers
  become: true
  vars:
    external_port: "{{ external_port }}"
    internal_port: "{{ internal_port }}"
    docker_image: "{{ docker_image }}"

  tasks:
    - name: Deploy with Docker
      command: docker run -d -p "{{ external_port }}":"{{ internal_port }}" "{{ docker_image }}"
