---
- name: Run deploy with k8s
  hosts: workers
  become: true
  vars:
    registry: "{{ registry }}"
    imageName: "{{ imageName }}"
    tag: "{{ tag }}"
    fullImageName: "{{ registry }}/{{ imageName }}:{{ tag }}"
  tasks:
    - name: create directory
      file:
        path: /home/radomkhoem/deployment
        state: directory
        mode: 0755

    - name: copy k8s deployment file
      copy:src:
        src: "../shellscript/deploy-k8s-CD/springdeploy.sh"
        dest: /home/radomkhoem/deployment/
        mode: '0755'

    - name: Run script to deploy
      command: sh /home/radomkhoem/deployment/springdeploy.sh "{{ fullImageName }}"
